openapi: 3.0.1
info:
  title: Neo4j Service
  description: Neo4j Service
  version: '2023-02-17T02:24:25Z'
servers:
  - url: https://zzi0l6eu68.execute-api.ap-southeast-1.amazonaws.com/{basePath}
    variables:
      basePath:
        default: /prod
paths:
  /getTopNetwork:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    node:
                      type: string
                      description: The name of the node
                    relationshipCount:
                      type: integer
                      description: The number of relationships for the node
  /getTopReferrer:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  customer:
                    type: object
                    properties:
                      Person:
                        type: object
                        properties:
                          referrerId:
                            type: integer
                            description: ID of the referrer
                          customerId:
                            type: integer
                            description: ID of the customer
                          name:
                            type: string
                            description: Name of the customer
                  referrals:
                    type: array
                    items:
                      type: object
                      properties:
                        Person:
                          type: object
                          properties:
                            referrerId:
                              type: integer
                              description: ID of the referrer
                            customerId:
                              type: integer
                              description: ID of the customer
                            name:
                              type: string
                              description: Name of the customer
                  closedReferrals:
                    type: array
                    items:
                      type: object
                      properties:
                        Person:
                          type: object
                          properties:
                            referrerId:
                              type: integer
                              description: ID of the referrer
                            customerId:
                              type: integer
                              description: ID of the customer
                            name:
                              type: string
                              description: Name of the customer
                  source:
                    type: object
                    properties:
                      Person:
                        type: object
                        properties:
                          referrerId:
                            type: integer
                            description: ID of the referrer
                          customerId:
                            type: integer
                            description: ID of the customer
                          name:
                            type: string
                            description: Name of the customer
